# Parameters for handling data such as BEV grid dimensions etc.

#####Paths
# Data
mcap_extract_path: "data/raw/mcap_extract"

radar_raw_path: "data/raw/mcap_extract/evt_0dpi0fwKmPDYNXBa/radar/front_right/"
imgs_raw_path: "data/raw/mcap_extract/evt_0dpi0fwKmPDYNXBa/camera/front_right/"
lidar_raw_path: "data/raw/mcap_extract/evt_0dpi0fwKmPDYNXBa/lidar/front_top"
seg_raw_path: "data/raw/mcap_extract/evt_0dpi0fwKmPDYNXBa/seg/front_right"
bbox_raw_path: "data/raw/mcap_extract/evt_0dpi0fwKmPDYNXBa/bbox/front_right"

transforms_path: "data/transforms"

camera_info: "data/raw/mcap_extract/evt_0dpi0fwKmPDYNXBa/camera/front_right/camera_info.npz"

processed_data_dir: "data/processed"
processed_data_dir_right: "data/processed/right"
processed_data_dir_left: "data/processed/left"

# mcap_path: "data/raw/agriRobotData.mcap"
mcap_path: "data/raw/bags/evt_0e8RSwkcSts5kEaF.mcap"
bags_path: "data/raw/bags"

# Visualization paths
finetuning_vis: 'reports/figures/finetuning'


# Models
depth_pro_weights: "/work3/s242723/.cache/depth-pro/depth_pro.pt"

# Top metric contender: moge
depth_model: "moge"      # can also be metric3d, depth_any, moge
                         # depth_any_rel, depth_pro, unidepth and zoe (zoe needs upgrade of timm)

# Frame for single predictions (development/visualizations)
img_frame: 140
radar_frame: 420
lidar_frame: 140

# BEV

direction: left

# # Original
# voxel_size: [2.5, 2.5, 25]
# point_cloud_range: [0, -10, -5, 40, 30, 20] # Right camera
# # Original end

# # Zoomed in (no treeline)
voxel_size: [1.5, 1.5, 25]
right_point_cloud_range: [1.5, -6, -5, 28.5, 21, 20] # Right camera
left_point_cloud_range: [1.5, -21, -5, 28.5, 6, 20]   # Left camera

hi_res_voxel: [0.1, 0.1, 25]
cam_channels: 3 # RBG
rad_channels: 11

# Point cloud specific 
lb_percent: [0, 5, 0]     # Lower bound percientiles of points to include (x,y,z)
ub_percent: [90, 95, 90]  # Upper bound percientiles of points to include (x,y,z)

# Filtering

#### ORIGINAL ####
# rcs_m2_filter: 0.13          # m^2
# snr_min: 15                  # dB
##################

#### TESTING ####
rcs_m2_filter: 0.00          # m^2
snr_min: 2                  # dB
################# 

min_dist: 5                  # m
max_dist: 120                # m
elevation_angle: -0.2        # rad

# Plot/figure folder
plot_folder: "reports/figures/"
plotting: False
meshlab_cam: False

# Depth calibration
calibration: 'lidar' # can also be radar or lidar
ransac_residual_threshold: 1.5
fit_beta: True
interp_depth_residuals: True # if depth completion is False, then scale (alpha, beta) will be fitted with ransac

# Number of radar scans to be used
num_radar_frames: 6 # 3 scans per image 

# Logging
logging: False
