# Finetuning-specific training config

batch_size: 128
num_workers: 8
prefetch_factor: 2
pin_memory: true
persistent_workers: true
train_mode: finetune

model_folder: "model_checkpoints"
 
# lr: 2e-7
# encoder_lr: 2e-7
lr: 2e-5
encoder_lr: 6e-5
weight_decay: 0.1
optimizer: adamw

max_epochs: 80  
min_epochs: 1
# warmup_steps: 500
warmup_steps: 200
gradient_clip_val: 1.0

# best_model_epoch=211_val_loss=4.6157_best
# pretrained_checkpoint: "best_model_epoch=22_val_loss=4.9486.ckpt" # 2 modalities
# pretrained_checkpoint: "best_model_epoch=57_val_loss=4.7586_bevFeat_512.ckpt" # With bevFeat
# pretrained_checkpoint: "best_3Dmodel_epoch=47_val_total_loss_unweighted=1.9904_tmp.ckpt" # With bevFeat 384 dim
pretrained_checkpoint: "best_model_epoch=86_val_total_loss_unweighted=1.9718.ckpt" # With bevFeat 384 dim rad overfit
freeze_encoder: true
load_pretrained_encoder: true

centerpoint_channels: 128
include_global_token: true

heatmap_weight: 0.1
offset_weight: 1.0
height_weight: 1.0
dim_weight: 1.0
rot_weight: 0.0

augment: true 
v_flip_rate: 0.5
h_flip_rate: 0.5
rot_rate: 0.5
rot_angle: [-180, 180]
viz_augment: false # Only input augment not bboxes

drop_path_rate: 0.1
drop_rate: 0.05
attn_drop_rate: 0.0

save_top_k: 1
continue_training: true
continue_checkpoint: best_3Dmodel_epoch=03_val_total_loss=2.3106.ckpt

# best_model: best_3Dmodel_epoch=02_val_total_loss=2.5790_absoluteBEST_better.ckpt # bevFeat

# best_model: best_3Dmodel_epoch=05_val_total_loss=2.5239_Å_unfreezed.ckpt # bevFeat 

# best_model: best_3Dmodel_epoch=18_val_total_loss=3.1483.ckpt # 2 modalities

# fresh-model-no-pretraining
# best_model: best_3Dmodel_epoch=08_val_total_loss=2.5287.ckpt
# best_model: best_3Dmodel_epoch=03_val_total_loss=2.6233.ckpt # No pretraining, only feat rad

# Pre-trained encoder, but centerpoint trained with unfreezed encoder from the start
# best_model: best_3Dmodel_epoch=04_val_total_loss=2.4421.ckpt

# Only radar and featBEV
best_model: best_3Dmodel_epoch=03_val_total_loss=2.3106.ckpt # This is better than the one below i think
# best_model: best_3Dmodel_epoch=00_val_total_loss=2.2566.ckpt

new_lr: true

matmul_precision: high
profile: false
profile_path: "profiling/finetune.prof"

# For visualization, single model pass
# sample_idx: 423
sample_idx: 300
direction: "right"
split: "val"
visualize: false
score_thresh: 0.3
ablation_test: false
max_pool: False # Only for ablation test

decode_score_thresh: 0.001 # For AP@50

use_circle_nms: true
min_radius: 0.3

num_backbone_layers: 2
modality_dropout: true
drop_radar_prob: 0.4
drop_cam_prob: 0.4
drop_feat_prob: 0.4
use_exp_dim: false
centerpoint_dropout: 0.5

# precision: 16-mixed
precision: 32

eval_split: "val"
eval_directions: ["right", "left"]

score_thresholds: [0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45]
center_dist_thresholds: [0.5, 1.0, 1.5, 2.0]
# center_dist_thresholds: [0.5, 1.0, 1.5, 2.0, 5.0]


drop_cam_inference: false
drop_rad_inference: false
drop_feat_inference: false

